name: face_shield
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  camera: ^0.10.3+2
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  shared_preferences: ^2.1.0
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "./assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
